// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afiwcpgvrlesqdjullfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmaXdjcGd2cmxlc3FkanVsbGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NDk4MDYsImV4cCI6MjA1NjIyNTgwNn0.gVcL_AXIrxyAeGiq9T_aiAWgQDwIERNqda3s4_1IhM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);